### ISSUE TITLE
What’s the tool used to make graphs such as the one in the read me ?

### ISSUE THREAD

**Issue by Crocmagnon** [itsolutionsfactory/dbcut#2]
What tool do you use to generate the database schema graphs ?

**Comment by SalemHarrache** [comment]
Hi @Crocmagnon 

I usually use the excellent eralchemy (https://github.com/Alexis-benoist/eralchemy).
As an alternative, you may have a look at sqlalchemy_schemadisplay : https://github.com/fschulze/sqlalchemy_schemadisplay

See you!
